package pkgMain;

import pkgcompte.Compte;
import pkgcompte.Titulaire;

public class Main {

	public static void main(String[] args) {
		//Création objet Titulaire
		Titulaire Tt= new Titulaire();
		//	Création objet Compte
		Compte cp = new Compte();


		public void effectuerUnretrait(Integer i_Integer_montant) throws Exception{
			String tmp = "traitement échoué!";
			if (i_Integer_montant == null) {throw new Exception("Le montant ["+i_Integer_montant+"] fourni est null, interdit!");}
			if (i_Integer_montant < 0) {throw new Exception("Le montant ["+i_Integer_montant+"] fourni est négatif!, interdit!");}
			if (this.i_Integer_solde - i_Integer_montant < 0) {throw new Exception("Le montant ["+i_Integer_montant+"] fourni est superieur au solde du compte, interdit!");}
			if (this.i_Integer_solde > 10000) {throw new Exception("Le montant ["+i_Integer_montant+"] fourni est superieur 10000€ autorisés par retrait, interdit!");}

			try {
				this.i_Integer_solde -= i_Integer_montant;
				tmp = "votre retrait a été effectué avec succès!";
			}
			catch(Exception e){
				tmp = e.toString();
			}
			finally {
				System.out.println(tmp + " traitement de la demande terminé!");
			}

		}
		public void effectuerUnvirement(Integer i_Integer_montantV) throws Exception{
			String tmp = "traitement échoué!";
			if (i_Integer_montantV == null) {throw new Exception("Le montant ["+i_Integer_montantV+"] fourni est null, interdit!");}
			if (i_Integer_montantV < 0) {throw new Exception("Le montant ["+i_Integer_montantV+"] fourni est négatif!, interdit!");}
			
			try {
				this.i_Integer_solde += i_Integer_montantV;
				tmp = "votre virement a été effectué avec succès!";
			}
			catch(Exception e){
				tmp = e.toString();
			}
			finally {
				System.out.println(tmp + " traitement de la demande terminé!");
			}

		

		//Fonctionnement du système try catch
		//try {
		//j'affiche un simple msg avant de faire le calcul
		//System.out.println("debut try");
		//effectuer une operation qui lance une exception
		//Titulaire Tt= new Titulaire();
		//if(Tt.i_idTitulaire != 0) {
		//System.out.println("l ["+i_idTitulaire+"]");
		//}else
		//System.out.println("id null");

		//} catch (Exception e) {
		//afficher un msg d'erreur

		//	}
		//finally {
		//System.out.println("ceci va s'executer meme si on est passé par le catch" );


		//}
	}


}
